### ISSUE TITLE
Use login events instead of provider to check login

### ISSUE THREAD

**Issue by thylo** [BeatSwitch/lock-laravel#10] opened 2015-01-19 16:11 UTC
Hi,

I use https://github.com/dingo/api to create a stateless API based on laravel. In order to "log in" to my app, I use one JWT auth token provided by https://github.com/tymondesigns/jwt-auth.

Problem is that in order to boot the `lockaware` trait the LockServiceProvider calls at "register time" the function `bootstrapAuthedUserLock`. 

``` php
/**
     * This will bootstrap the lock instance for the authed user
     */
    protected function bootstrapAuthedUserLock()
    {

        $this->app->bindShared('lock', function ($app) {
            // If the user is logged in, we'll make the user lock aware and register its lock instance.
            if ($app['auth']->check()) {

                // Get the lock instance for the authed user.
                $lock = $app['lock.manager']->caller($app['auth']->user());

                // Enable the LockAware trait on the user.
                $app['auth']->user()->setLock($lock);

                return $lock;
            }
            // Get the caller type for the user caller.
            $userCallerType = $app['config']->get('lock-laravel::user_caller_type');

            // Bootstrap a SimpleCaller object which has the "guest" role.
            return $app['lock.manager']->caller(new SimpleCaller($userCallerType, 0, ['guest']));
        });

        $this->app->alias('lock', 'BeatSwitch\Lock\Lock');
    }
```

As my api is stateless, I do not rely on the session cache to login. The login is done at "request time". So at the time Lock is boostrapped, I'm not already logged in. 

Would It then be possible to delay the call to this function until the "auth.login" is dispatched ? As seen here `http://laravel.com/docs/4.2/events#basic-usage`

BTW Thanks a lot for the package ;-)

**Comment by kirkbushell** [comment] 2015-03-09 13:18
I think auth.login is only fired when a user actually logs in - not on every page request.

As a result, your suggestion would break on every other installation.

That said, perhaps there's a way we can satisfy both requirements?

**Comment by kirkbushell** [comment] 2015-03-09 13:22
What you can do in the meantime, however - is do the binding yourself by extending the binding once you're ready:

```php
App::extend('lock', function($lock, $app) {
    return $app['lock.manager']->caller($callerObject);
});
```

**Comment by kirkbushell** [comment] 2015-03-10 21:25
Playing around with this a bit more - I think there's a bigger issue here - I can't see, to be able to set my permissions as the user is never available via Auth::user() (which I use to get the user's roles).

**Comment by driesvints** [comment] 2015-03-10 23:07
@kirkbushell do you mean that the user is gone from the Auth facade or that the `LockAware` methods aren't accessible on the Auth::user() call?

**Comment by kirkbushell** [comment] 2015-03-10 23:21
In the permissions call in lock-laravel, I'm getting the logged-in user (after doing a check) - but it always returns null. The permissions are called from within a boot method, I would expect it to be available by then. Any idea what's going on?

**Comment by driesvints** [comment] 2015-03-10 23:32
I think I know what the problem is. The permissions probably aren't set yet because the boot event happens after the register. I'm gonna rewrite this implementation to a different class. Will need to wait until tomorrow or bit later I'm afraid.

**Comment by kirkbushell** [comment] 2015-03-10 23:41
I can sort this out now @driesvints lemme know what's going on and I'll fix. I don't think putting in a the register method or anything will fix it...

Boot is the right approach here for loading the permissions, as we can safely assume the rest o the application has at least registered its dependencies and provided bindings.

**Comment by driesvints** [comment] 2015-04-17 22:16
I'm just gonna be honest with you guys. I don't have the time atm to look into this and probably won't have for the upcoming weeks. If anyone can take the time to figure this out, that'd be great :confused:

**Comment by driesvints** [comment] 2016-12-18 12:24
Better late then never I guess. This should be fixed in the latest release. There is a middleware now to bootstrap the LockAware trait.

**Closed by driesvints** 2016-12-18 12:24 UTC
